function current_conf = prune(current_conf)

%   PRUNE -- Remove extraneous fields from config file.
%
%     conf = ... prune() loads the current config file and removes
%     extraneous fields, that is, fields that are present in the saved
%     config file, but not in the file that would be generated by ...
%     .config.create().
%
%     conf = ... prune( conf ) uses the config file `conf` instead of the
%     saved config file.
%
%     See also scnc.config.reconcile
%
%     IN:
%       - `current_conf` (struct) |OPTIONAL|
%     OUT:
%       - `current_conf` (struct)

if ( nargin < 1 || isempty(current_conf) )
  current_conf = scnc.config.load();
else
  scnc.util.assertions.assert__is_config( current_conf );
end

created = scnc.config.create( false );

extraneous = scnc.config.diff( created, false, current_conf );

for i = 1:numel(extraneous)
  split = strsplit( extraneous{i}, '.' );
  split( cellfun(@isempty, split) ) = [];
  
  base = split(1:end-1);
  target = split{end};
  
  if ( isempty(base) )
    current_conf = rmfield( current_conf, target );
  else
    base = strjoin( base, '.' );
    cmd = sprintf( 'current_conf.%s = rmfield(current_conf.%s, target);' ...
      , base, base );
    eval( cmd );
  end
end

end